name: MCP Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Playwrightインストール
          pip install playwright
          playwright install --with-deps chromium

      - name: Smoke Test MCP server
        run: |
          echo '{"jsonrpc": "2.0", "id": "test1", "method": "tools/list", "params": {}}' \
          | python mcp/mcp_server.py || exit 1
